version: '3'

services:
    app:
      image: docker-nextjs-dev
      build: .
      ports:
        - 3000:3000
      volumes:
        - ./src:/app/src
        - ./public:/app/public
        - ./components:/app/components
        - ./pages:/app/pages
        - ./styles:/app/styles
      env_file:
      - .env.production
